config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    resource :likes, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count
  validates :user_id, uniqueness: {
    scope: :post_id,
    message: 'は同じ投稿に2回以上いいねできません'
  }

  # 自分の投稿に「いいね！」できないようにする
  validate :my_post_cannot_like

  private

  def my_post_cannot_like
    errors.add(:base, '自分の投稿にいいねはできません') if user_id == post.user_id
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  # post.liked_users で post を「いいね!」しているユーザーの一覧を取得できるようになる
  has_many :liked_users, through: :likes, source: :user
  validates :content, presence: true
  # post を user が「いいね！」しているときは「true」，「いいね」していないときは「false」
  def liked_by?(user)
    likes.any? { |like| like.user_id == user.id }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  # user.liked_posts で user が「いいね!」しているメッセージの一覧を取得できるようになる
  has_many :liked_posts, through: :likes, source: :post
  has_many :liked_posts, through: :likes, source: :post
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    current_user.likes.create!(post_id: params[:post_id])
    @post = Post.find(params[:post_id])
  end

  def destroy
    current_user.likes.find_by(post_id: params[:post_id]).destroy!
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]

  def index
    @posts = Post.includes(:user, :likes).order(:created_at)
  end

  def new
    @post = Post.new
  end

  def create
    post = current_user.posts.create!(post_params)
    redirect_to post
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit; end

  def update
    @post.update!(post_params)
    redirect_to @post
  end

  def destroy
    @post.destroy!
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def set_post
    @post = current_user.posts.find_by(params[:id])
    redirect_to root_path, alert: '権限がありません' if @post.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%= link_to "一覧ページ", root_path %>
  <%= link_to "新規投稿ページ", new_post_path %>
  <%= link_to "アカウント編集", edit_user_registration_path %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  <%= "【ログイン中のアドレス】#{current_user.email}" %>
<% else %>
  <%= link_to "新規登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LikeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
document.getElementById('post-<%= @post.id %>').innerHTML = '<%= j render("posts/like", post: @post) %>'

app/views/likes/destroy.js.erb
document.getElementById('post-<%= @post.id %>').innerHTML = '<%= j render("posts/dislike", post: @post) %>'

app/views/posts/_dislike.html.erb
<%# 「いいね」していない（クリックすると「いいね！」にする） %>
<%= link_to "☆", post_likes_path(post), method: :post, remote: true %>
<%= post.likes_count %>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
  <%= form.label :content %>
  <%= form.text_field :content, required: true %>
  <%= form.submit "送信" %>
<% end %>

app/views/posts/_like.html.erb
<%# 「いいね！」済み（クリックすると「いいね」解除） %>
<%= link_to "★", post_likes_path(post), method: :delete, remote: true %>
<%= post.likes_count %>

app/views/posts/_post.html.erb
<div>
  <p>【メールアドレス】 <%= post.user.email %></p>
  <p>【内容】 <%= post.content %></p>
  <p id="post-<%= post.id %>">
    <% if post.liked_by?(current_user) %>
      <%= render "like", post: post %>
    <% else %>
      <%= render "dislike", post: post %>
    <% end %>
  </p>
  <p>
    <%= link_to "詳細", post %>
    <% if current_user.id == post.user_id %>
      <%= link_to "編集", edit_post_path(post) %>
      <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "削除しますか？" } %>
    <% end %>
  </p>
</div>
<hr>

app/views/posts/edit.html.erb
<h1>編集</h1>
<%= render "form" %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<%= render @posts %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>
<p>【メールアドレス】 <%= @post.user.email %></p>
<p>【内容】 <%= @post.content %></p>
<p>【作成日時】 <%= l @post.created_at %></p>
<p id="post-<%= @post.id %>">
  <% if @post.liked_by?(current_user) %>
    <%= render "like", post: @post %>
  <% else %>
    <%= render "dislike", post: @post %>
  <% end %>
</p>
<% if current_user.id == @post.user_id %>
  <p>
    <%= link_to "編集", edit_post_path(@post) %>
    <%= link_to "削除", post_path(@post), method: :delete, data: { confirm: "削除しますか？" } %>
  </p>
<% end %>
<p><%= link_to "投稿一覧へ", posts_path %></p>